[2024-10-14 16:02:49,107] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-14 16:02:49,111] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-14 16:02:49,111] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-14 16:02:49,111] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-14 16:02:49,111] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-14 16:02:49,124] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2024-10-07 00:00:00+00:00
[2024-10-14 16:02:49,130] {standard_task_runner.py:52} INFO - Started process 39147 to run task
[2024-10-14 16:02:49,135] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp7u1c46gf', '--error-file', '/tmp/tmpz773rgmn']
[2024-10-14 16:02:49,136] {standard_task_runner.py:80} INFO - Job 25: Subtask extrai_dados
[2024-10-14 16:02:49,172] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-07T00:00:00+00:00 [running]> on host luan-capella
[2024-10-14 16:02:49,211] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-07T00:00:00+00:00
[2024-10-14 16:02:49,851] {python.py:173} INFO - Done. Returned value was: None
[2024-10-14 16:02:49,865] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20241007T000000, start_date=20241014T190249, end_date=20241014T190249
[2024-10-14 16:02:49,905] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-14 16:02:49,921] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14 16:07:07,405] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-14 16:07:07,409] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-14 16:07:07,409] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-14 16:07:07,409] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-14 16:07:07,409] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-14 16:07:07,422] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2024-10-07 00:00:00+00:00
[2024-10-14 16:07:07,427] {standard_task_runner.py:52} INFO - Started process 41228 to run task
[2024-10-14 16:07:07,430] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpc8p0dbua', '--error-file', '/tmp/tmpzhwt97vh']
[2024-10-14 16:07:07,431] {standard_task_runner.py:80} INFO - Job 31: Subtask extrai_dados
[2024-10-14 16:07:07,468] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-07T00:00:00+00:00 [running]> on host luan-capella
[2024-10-14 16:07:07,512] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-07T00:00:00+00:00
[2024-10-14 16:07:08,534] {python.py:173} INFO - Done. Returned value was: None
[2024-10-14 16:07:08,548] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20241007T000000, start_date=20241014T190707, end_date=20241014T190708
[2024-10-14 16:07:08,604] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-14 16:07:08,634] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
