[2025-02-03 22:20:36,180] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-02-03 22:20:36,184] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-02-03 22:20:36,184] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:20:36,184] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-02-03 22:20:36,184] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:20:36,198] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2025-01-20 00:00:00+00:00
[2025-02-03 22:20:36,203] {standard_task_runner.py:52} INFO - Started process 42376 to run task
[2025-02-03 22:20:36,206] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp65q7vndk', '--error-file', '/tmp/tmp42syqk3s']
[2025-02-03 22:20:36,206] {standard_task_runner.py:80} INFO - Job 74: Subtask extrai_dados
[2025-02-03 22:20:36,243] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2025-01-20T00:00:00+00:00 [running]> on host luan-capella
[2025-02-03 22:20:36,286] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2025-01-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-01-20T00:00:00+00:00
[2025-02-03 22:20:37,120] {python.py:173} INFO - Done. Returned value was: None
[2025-02-03 22:20:37,133] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20250120T000000, start_date=20250204T012036, end_date=20250204T012037
[2025-02-03 22:20:37,180] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-03 22:20:37,194] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
